# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9c4cf448-62b7-4c60-b7c6-d17902e0e180";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-9c4cf448-62b7-4c60-b7c6-d17902e0e180".device = "/dev/disk/by-uuid/9c4cf448-62b7-4c60-b7c6-d17902e0e180";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-9c4cf448-62b7-4c60-b7c6-d17902e0e180";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-9c4cf448-62b7-4c60-b7c6-d17902e0e180";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9CE2-FB90";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-302bb0b3-9f66-4e72-8de2-198e5896f944"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
